version: 2.1

executors:
  main_exe:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

jobs:
  style_checker:
    executor: main_exe
    steps:
      - checkout
      - run:
          name: Check Google style
          command: mvn checkstyle:check

  compile:
    executor: main_exe
    steps:
      - checkout
      - run:
          name: Compiles the project
          command: mvn compile

  test:
    executor: main_exe
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: mvn test

  package:
    executor: main_exe
    steps:
      - checkout
      - run: mvn package

  deploy:
    executor: main_exe
    steps:
      - checkout
      - run:
          name: Directory for deploy
          command: mkdir deploy
      - run:
          name: Deploy
          command: mvn deploy

workflows:
  main_flow:
    jobs:
      - style_checker
      - compile:
          requires:
            - style_checker
      - test:
          requires:
            - compile
      - package:
          requires:
            - compile
      - deploy:
          requires:
            - test
            - package