version: 2.1

executors:
  main_exe:
    docker:
      - image: circleci/openjdk:8-jdk-stretch
references:
  # The directory containing our maven dependencies
  - &maven_home /root/.m2/repository/
  # THe name of the key used for the maven dependency cache. Uniquely identified by repo name and checksum of all project poms.
  - &maven_cache_key v1-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-maven-dependencies-{{ checksum "/tmp/maven-checksum.txt" }}

commands:
  generate_maven_checksum:
    description: Generate a checksum of the main project pom and any sub-module poms
    steps:
      - run:
          name: Create a file containing a checksum of all pom.xml files in the project as well as the executor type.
          command: |
            sha1sum pom.xml **/pom.xml > /tmp/maven-checksum.txt || true
            echo "executor: ${EXECUTOR_TYPE}" >> /tmp/maven-checksum.txt
  save_maven_dependencies:
    description: Persist maven dependencies. Cache key uses a combined checksum of the main pom and any sub-module poms.
    steps:
      - generate_maven_checksum
      - save_cache:
          key: *maven_cache_key
          paths:
            - *maven_home

  restore_maven_dependencies:
    description: Restore cached maven dependencies. Cache key uses a combined checksum of the main pom and any sub-module poms.
    steps:
      - generate_maven_checksum
      - restore_cache:
          key: *maven_cache_key
      - run:
          name: Resolve maven dependencies
          command: |
            mvn --batch-mode \
              -DskipTests -Ddockerfile.skip -Dmaven.javadoc.skip -Dcheckstyle.skip -Djacoco.skip -Dspotbugs.skip \
              clean install dependency:resolve-plugins \
              dependency:go-offline

jobs:
  validate:
    executor: main_exe
    steps:
      - checkout
      - run:
          name: Check Google style and validates
          command: mvn validate
      - generate_maven_checksum
      - save_maven_dependencies
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  compile:
    executor: main_exe
    steps:
      - attach_workspace:
          at: .
      - restore_maven_dependencies
      - save_maven_dependencies
      - run:
          name: Compiles the project
          command: mvn compile
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  test:
    executor: main_exe
    steps:
      - attach_workspace:
          at: .
      - restore_maven_dependencies
      - save_maven_dependencies
      - run:
          name: Unit Tests
          command: mvn test
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  package:
    executor: main_exe
    steps:
      - attach_workspace:
          at: .
      - checkout
      - restore_maven_dependencies
      - save_maven_dependencies
      - run: mvn package
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  verify:
    executor: main_exe
    steps:
      - attach_workspace:
          at: .
      - restore_maven_dependencies
      - save_maven_dependencies
      - run:
          name: Verify
          command: mvn verify
      - persist_to_workspace:
          root: .
          paths:
            - '*'

  deploy:
    executor: main_exe
    steps:
      - attach_workspace:
          at: .
      - restore_maven_dependencies
      - save_maven_dependencies
      - run:
          name: Deploy
          command: mvn deploy

workflows:
  main_flow:
    jobs:
      - validate
      - compile:
          requires:
            - validate
      - test:
          requires:
            - compile
      - package:
          requires:
            - test
      - verify:
          requires:
            - package
      - deploy:
          filters:
            branches:
              only:
                - master
          requires:
            - test
            - package