version: 2.1

executors:
  main_exe:
    docker:
      - image: circleci/openjdk:8-jdk-stretch

jobs:
  validate:
    executor: main_exe
    steps:
      - checkout
      - run:
          name: Check Google style and validates
          command: mvn validate

  compile:
    executor: main_exe
    steps:
      - checkout
      - run:
          name: Compiles the project
          command: mvn compile

  test:
    executor: main_exe
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: mvn test

  package:
    executor: main_exe
    steps:
      - checkout
      - run: mvn package

  deploy:
    executor: main_exe
    steps:
      - checkout
      - run:
          name: Deploy
          command: mvn deploy

workflows:
  main_flow:
    jobs:
      - validate
      - compile:
          requires:
            - validate
      - test:
          requires:
            - compile
      - package:
          requires:
            - test
      - deploy:
          requires:
            - test
            - package